### PR TITLE
Port to Python3 [GCI]

### PR DESCRIPTION
**Pull request by srevinsaju**
Ported to Python and tested collaboration. Does an odd thing before and after porting. If the person who hosts the Poll, votes, his vote is counted as 1, if the outsider votes, the rest of the votes are assigned to him. @quozl @chimosky please review. Thanks

### CODE REVIEW

**Comment by quozl** [comment]
So a sharer's vote infects joiners' votes?  Interesting.  Not at all what we would want to release.  Please raise an issue with a step by step way to reproduce.

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Comment by srevinsaju** [comment]
@quozl, the maximum I can test is with two VMs. as there are probably only 2 ppl in my neighborhood, and I have set the maximum number of ppl to be 10, it assumes the rest of the vote to be voted. there is not another user to vote into it, max 2 of the VMs have already voted . one of them option A, another option B. the last one who voted, takes the rest of the pie graph. it would better to test with 4-5 sugar desktops to confirm if this is the issue, or I might be doing some wrong step to vote

**Comment by quozl** [comment]
Oops, `exec` in activity.info wasn't changed, so testing did use Python 2, consequently quite a few regressions were missed.  I've fixed them.
 
* 0b696b2 ("Port to Python 3 - missed setup.py")
* 96699fb ("Port to Python 3 - missing exec")
* dc9dee5 ("Port to Python 3 - hash digests")
* 539d4ae ("Port to Python 3 - Gtk.CssProvider wants bytes")
* db325e2 ("Port to Python 3.8 - fix SyntaxWarning on using is with literals")

I didn't have time for a coverage based test.

**Pull request merged**
